generator:
    # Entity or Document
    class:              TheClass

    # Theme
    theme:              AdminGeneratorBundle

#    non_verbose_templates: true
#    with_show:             false
#    singular:              ~
#    plural:                ~
#    route_prefix:          funcionario
#    with_doctrine_route:   true
#    actions_base_class:    sfActions

    actions:            ~
    fields:             ~
    list:
        title:          "Listing %%records%%"
        method:         find
        count_method:   count
        display:        ~
        # grid or stacked, default grid
        layout:         grid
        sort:           ~
        max_per_page:   ~
        object_actions: ~
        batch_actions:  ~
    form:
        type:           ~
    edit:
        title:          "Edditing"
        display:        ~
#        actions:        ~
    new:
        title:          "New"
        display:        ~
#         actions:       ~
    filter:
        type:           ~
        display:        ~
