parameters:
#    coregen_admin_generator.example.class: Coregen\AdminGeneratorBundle\Example

services:
#    coregen_admin_generator.example:
#        class: %coregen_admin_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
