parameters:
#    coregen_admin_generator.example.class: Coregen\AdminGeneratorBundle\Example

services:
#    coregen.admin_generator:
#        class: Coregen\AdminGeneratorBundle\Generator\Generator
#        arguments: ["Symfony\Component\DependencyInjection\Loader\YamlFileLoader"]
