parameters:
    coregen_generator.class: Coregen\AdminGeneratorBundle\Generator\Generator
    coregen_generator_odm_pager.class: Coregen\AdminGeneratorBundle\ODM\Pager
    coregen_generator_orm_pager.class: Coregen\AdminGeneratorBundle\ORM\Pager

services:
    coregen.generator:
        class:     %coregen_generator.class%

    coregen.orm.pager:
        class:     %coregen_generator_orm_pager.class%
        arguments: [@doctrine]
    coregen.odm.pager:
        class:     %coregen_generator_odm_pager.class%
        arguments: [@doctrine, @coregen.generator]

